First page
Marra2342/Portfolio pull request #1
Opened 2022-06-01 18:05 UTC by Marra2342

Portfolio Project

2022-06-01 20:58 UTC, vic778 requested changes
## Hello @Marra2342 

Good job so far! I know you have worked hard on making this project.  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [x] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 20:58 UTC, vic778 commented on README.md
> +# Project Description
- [OPTIONAL] Kindly you don't need to introduce the description.  basically after the Title of the project we have  the description. to make your README more professional i can advance you to delete this line

2022-06-01 20:58 UTC, vic778 commented on README.md
>  To get a local copy up and running follow these simple example steps.
- [ ] Kindly enumerate those steps to get the project locally. Imagine someone who don;t know anything about GitHub and he want to clone your project. try to explain how he can clone your project using witch code, if he will need to install dependencies to run some tests, try to explain how those this works

2022-06-01 20:58 UTC, vic778 commented on css/styles.css
> +  font-size: 60px;
- [ ] Kindly decrease the font-size because it cover even the `<p>` as you can see the screenshot bellow  
Your design

![Screenshot from 2022-06-01 23-49-59](https://user-images.githubusercontent.com/77842237/171499085-612dc20a-15a7-4222-953d-1a4dfa6f5abf.png)

2022-06-01 20:58 UTC, vic778 commented on index.html
> +    <nav class="des"></nav>
- [ ] Kindly remove this line. it seems like it doesn't contain anything else

2022-06-01 20:58 UTC, vic778 commented on index.html
> +    </nav>
- [ ] Please instead of using `<nav>` change it to `<div>` because the nav is ready in the header. when you're using `html semantics` the browser will know with section layout according to how the page was built

2022-06-01 22:53 UTC, vic778 commented on index.html
> +    </nav>
please if you have any questions feel free to text me. i will be happy to answer you as well :1st_place_medal:

2022-06-01 23:40 UTC, Kossi-stack requested changes
## Hi @Marra2342,

**Good job so far! 👍🏻**
There are some issues that you still need to work on to go to the next project but you are almost there!💪

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966](https://user-images.githubusercontent.com/81444338/170121142-a9f93bb7-38bb-45cc-8327-aab2501ef90a.gif)

## To Highlight

✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Required Changes ♻️

 _Check the comments under the review for more changes_.

## Optional suggestions
- [ ] Kindly edit the PR's title to something more descriptive. it can be "Portfolio: setup and mobile version skeleton" or Portfolio: setup and mobile version skeleton PR".
 - [ ] Kindly add a descriptive pull request message, This helps other programmers who want to take a look at your code to understand what changes you made to a particular branch, you can find an example [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects).

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-06-01 23:40 UTC, Kossi-stack commented on .gitignore
> +test.yml
- [ ] Kindly fix this is test.md not .yml

2022-06-01 23:40 UTC, Kossi-stack commented on css/styles.css
> +  font-style: normal;
- [ ] Kindly check Figma design [here](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122).
- On the Figma design i think the font-size is not _60px but 40px_ and also work on the margin
- Your Design
![Capturegrace](https://user-images.githubusercontent.com/81444338/171518248-72c65988-f381-4e1f-b360-236677e9b32c.PNG)
- Figma Design
![Capturefigrace](https://user-images.githubusercontent.com/81444338/171518279-d883d1d1-2b97-4690-8278-22c7ca17a059.PNG)

2022-06-02 19:22 UTC, bimbolabuari approved these changes
Hi @Marra2342, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
- Kindly edit the PR's title to something more descriptive. it can be "Portfolio: setup and mobile version skeleton" or Portfolio: setup and mobile version skeleton PR".
 - Kindly add a descriptive pull request message, This helps other programmers who want to take a look at your code to understand what changes you made to a particular branch, you can find an example [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md#5-basic-rules-to-follow-in-microverse-projects).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 19:26 UTC, smunozmo requested changes
Hi @Marra2342, 👋  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 👏 

- Great work using the right GitHub Flow.
- Your README looks professional, well done!
- Commits are descriptive, good work.
- Linters are working properly, great job!


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [OPTIONAL] It would be great to add a meaningful title to your Pull Request like 'Portfolio: First section" and a description talking about what you have done in this milestone, this will make your repo look more professional.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

<img src="https://media1.giphy.com/media/z5cNqbFbMTDA4/giphy.gif"/>


Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

⚠️  **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 19:26 UTC, smunozmo commented on index.html
> +    <nav class="des"></nav>
- [ ] You are almost there! However, as the previous reviewer said, it would be better to remove any unused code like this line, this will make your code cleaner.

2022-06-02 19:26 UTC, smunozmo commented on README.md
> -> Description the project.
[OPTIONAL] Nice job documenting your project! It would be great to add a description, just tell the visitors what is your project about, this is a good way to show your work.

2022-06-02 19:48 UTC, merged